// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	LogoUrl       *string            `json:"logo_url"`
	Description   *string            `json:"description"`
	Website       *string            `json:"website"`
	Category      string             `json:"category"`
	Tags          []string           `json:"tags"`
	FoundedYear   *int32             `json:"founded_year"`
	HqLocation    *string            `json:"hq_location"`
	EmployeeRange *string            `json:"employee_range"`
	FundingStage  *string            `json:"funding_stage"`
	EloRating     int32              `json:"elo_rating"`
	TotalVotes    int32              `json:"total_votes"`
	Wins          int32              `json:"wins"`
	Losses        int32              `json:"losses"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CompanyComment struct {
	ID                int32              `json:"id"`
	CompanyID         int32              `json:"company_id"`
	Content           string             `json:"content"`
	IsCurrentEmployee *bool              `json:"is_current_employee"`
	SessionID         *string            `json:"session_id"`
	Upvotes           int32              `json:"upvotes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type CompanyRating struct {
	ID        int32              `json:"id"`
	CompanyID int32              `json:"company_id"`
	Criterion string             `json:"criterion"`
	Score     int32              `json:"score"`
	SessionID *string            `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vote struct {
	ID        int32              `json:"id"`
	WinnerID  int32              `json:"winner_id"`
	LoserID   int32              `json:"loser_id"`
	SessionID *string            `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    *string            `json:"user_id"`
}
