// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CompanyExists(ctx context.Context, id int32) (bool, error)
	CountComments(ctx context.Context) (int64, error)
	CountCompanies(ctx context.Context) (int64, error)
	CountCompaniesByCategory(ctx context.Context, category string) (int64, error)
	CountRatings(ctx context.Context) (int64, error)
	CountUsersWithVotes(ctx context.Context) (int64, error)
	CountVotes(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (CompanyComment, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (CompanyRating, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (CreateVoteRow, error)
	GetAggregatedRatings(ctx context.Context, companyID int32) ([]GetAggregatedRatingsRow, error)
	GetCategories(ctx context.Context) ([]GetCategoriesRow, error)
	GetCompanyByID(ctx context.Context, id int32) (Company, error)
	GetCompanyBySlug(ctx context.Context, slug string) (Company, error)
	GetCompanyComments(ctx context.Context, companyID int32) ([]CompanyComment, error)
	GetCompanyEloRating(ctx context.Context, id int32) (int32, error)
	GetCompanyIDBySlug(ctx context.Context, slug string) (int32, error)
	GetCompanyRank(ctx context.Context, eloRating int32) (int32, error)
	GetDistinctCategories(ctx context.Context) ([]string, error)
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]Company, error)
	GetLeaderboardByCategory(ctx context.Context, arg GetLeaderboardByCategoryParams) ([]Company, error)
	GetRandomMatchup(ctx context.Context) ([]Company, error)
	GetRandomMatchupByCategory(ctx context.Context, category string) ([]Company, error)
	GetUserLeaderboard(ctx context.Context, arg GetUserLeaderboardParams) ([]GetUserLeaderboardRow, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListCompaniesByCategory(ctx context.Context, category string) ([]Company, error)
	SearchCompanies(ctx context.Context, name string) ([]Company, error)
	SearchCompaniesByCategory(ctx context.Context, arg SearchCompaniesByCategoryParams) ([]Company, error)
	UpdateCompanyAfterLoss(ctx context.Context, arg UpdateCompanyAfterLossParams) error
	UpdateCompanyAfterWin(ctx context.Context, arg UpdateCompanyAfterWinParams) error
	UpvoteComment(ctx context.Context, id int32) (CompanyComment, error)
}

var _ Querier = (*Queries)(nil)
