// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Company represents an AI company
type Company struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	LogoUrl       *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Website       *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Category      string                  `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string                `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	FoundedYear   *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	HqLocation    *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=hq_location,json=hqLocation,proto3" json:"hq_location,omitempty"`
	EmployeeRange *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=employee_range,json=employeeRange,proto3" json:"employee_range,omitempty"`
	FundingStage  *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=funding_stage,json=fundingStage,proto3" json:"funding_stage,omitempty"`
	EloRating     int32                   `protobuf:"varint,13,opt,name=elo_rating,json=eloRating,proto3" json:"elo_rating,omitempty"`
	TotalVotes    int32                   `protobuf:"varint,14,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	Wins          int32                   `protobuf:"varint,15,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int32                   `protobuf:"varint,16,opt,name=losses,proto3" json:"losses,omitempty"`
	Rank          int32                   `protobuf:"varint,17,opt,name=rank,proto3" json:"rank,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Company) GetLogoUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.LogoUrl
	}
	return nil
}

func (x *Company) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Company) GetWebsite() *wrapperspb.StringValue {
	if x != nil {
		return x.Website
	}
	return nil
}

func (x *Company) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Company) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Company) GetFoundedYear() *wrapperspb.Int32Value {
	if x != nil {
		return x.FoundedYear
	}
	return nil
}

func (x *Company) GetHqLocation() *wrapperspb.StringValue {
	if x != nil {
		return x.HqLocation
	}
	return nil
}

func (x *Company) GetEmployeeRange() *wrapperspb.StringValue {
	if x != nil {
		return x.EmployeeRange
	}
	return nil
}

func (x *Company) GetFundingStage() *wrapperspb.StringValue {
	if x != nil {
		return x.FundingStage
	}
	return nil
}

func (x *Company) GetEloRating() int32 {
	if x != nil {
		return x.EloRating
	}
	return 0
}

func (x *Company) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *Company) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *Company) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *Company) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Company) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CompanyList is a list of companies
type CompanyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyList) Reset() {
	*x = CompanyList{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyList) ProtoMessage() {}

func (x *CompanyList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyList.ProtoReflect.Descriptor instead.
func (*CompanyList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyList) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

// Vote represents a head-to-head vote
type Vote struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WinnerId      int32                   `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	LoserId       int32                   `protobuf:"varint,3,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`
	SessionId     *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Vote) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vote) GetWinnerId() int32 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *Vote) GetLoserId() int32 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *Vote) GetSessionId() *wrapperspb.StringValue {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *Vote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// VoteRequest represents a voting request
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      int32                  `protobuf:"varint,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	LoserId       int32                  `protobuf:"varint,2,opt,name=loser_id,json=loserId,proto3" json:"loser_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *VoteRequest) GetWinnerId() int32 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *VoteRequest) GetLoserId() int32 {
	if x != nil {
		return x.LoserId
	}
	return 0
}

func (x *VoteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// VoteResponse represents the voting response with updated ELOs
type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winner        *Company               `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	Loser         *Company               `protobuf:"bytes,2,opt,name=loser,proto3" json:"loser,omitempty"`
	WinnerEloDiff int32                  `protobuf:"varint,3,opt,name=winner_elo_diff,json=winnerEloDiff,proto3" json:"winner_elo_diff,omitempty"`
	LoserEloDiff  int32                  `protobuf:"varint,4,opt,name=loser_elo_diff,json=loserEloDiff,proto3" json:"loser_elo_diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *VoteResponse) GetWinner() *Company {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *VoteResponse) GetLoser() *Company {
	if x != nil {
		return x.Loser
	}
	return nil
}

func (x *VoteResponse) GetWinnerEloDiff() int32 {
	if x != nil {
		return x.WinnerEloDiff
	}
	return 0
}

func (x *VoteResponse) GetLoserEloDiff() int32 {
	if x != nil {
		return x.LoserEloDiff
	}
	return 0
}

// MatchupPair represents two companies for voting
type MatchupPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company1      *Company               `protobuf:"bytes,1,opt,name=company1,proto3" json:"company1,omitempty"`
	Company2      *Company               `protobuf:"bytes,2,opt,name=company2,proto3" json:"company2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchupPair) Reset() {
	*x = MatchupPair{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchupPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchupPair) ProtoMessage() {}

func (x *MatchupPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchupPair.ProtoReflect.Descriptor instead.
func (*MatchupPair) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *MatchupPair) GetCompany1() *Company {
	if x != nil {
		return x.Company1
	}
	return nil
}

func (x *MatchupPair) GetCompany2() *Company {
	if x != nil {
		return x.Company2
	}
	return nil
}

// CompanyRating represents a rating for a specific criterion
type CompanyRating struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     int32                   `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Criterion     string                  `protobuf:"bytes,3,opt,name=criterion,proto3" json:"criterion,omitempty"`
	Score         int32                   `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	SessionId     *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyRating) Reset() {
	*x = CompanyRating{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRating) ProtoMessage() {}

func (x *CompanyRating) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRating.ProtoReflect.Descriptor instead.
func (*CompanyRating) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *CompanyRating) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompanyRating) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *CompanyRating) GetCriterion() string {
	if x != nil {
		return x.Criterion
	}
	return ""
}

func (x *CompanyRating) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CompanyRating) GetSessionId() *wrapperspb.StringValue {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CompanyRating) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// RatingRequest represents a rating submission
type RatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int32                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Criterion     string                 `protobuf:"bytes,2,opt,name=criterion,proto3" json:"criterion,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingRequest) Reset() {
	*x = RatingRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingRequest) ProtoMessage() {}

func (x *RatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingRequest.ProtoReflect.Descriptor instead.
func (*RatingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *RatingRequest) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *RatingRequest) GetCriterion() string {
	if x != nil {
		return x.Criterion
	}
	return ""
}

func (x *RatingRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RatingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// AggregatedRating represents aggregated ratings for a criterion
type AggregatedRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criterion     string                 `protobuf:"bytes,1,opt,name=criterion,proto3" json:"criterion,omitempty"`
	AverageScore  float64                `protobuf:"fixed64,2,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	TotalRatings  int32                  `protobuf:"varint,3,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedRating) Reset() {
	*x = AggregatedRating{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedRating) ProtoMessage() {}

func (x *AggregatedRating) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedRating.ProtoReflect.Descriptor instead.
func (*AggregatedRating) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *AggregatedRating) GetCriterion() string {
	if x != nil {
		return x.Criterion
	}
	return ""
}

func (x *AggregatedRating) GetAverageScore() float64 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *AggregatedRating) GetTotalRatings() int32 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

// AggregatedRatingList is a list of aggregated ratings
type AggregatedRatingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*AggregatedRating    `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedRatingList) Reset() {
	*x = AggregatedRatingList{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedRatingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedRatingList) ProtoMessage() {}

func (x *AggregatedRatingList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedRatingList.ProtoReflect.Descriptor instead.
func (*AggregatedRatingList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *AggregatedRatingList) GetRatings() []*AggregatedRating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

// CompanyComment represents a comment/review
type CompanyComment struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Id                int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId         int32                   `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Content           string                  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsCurrentEmployee bool                    `protobuf:"varint,4,opt,name=is_current_employee,json=isCurrentEmployee,proto3" json:"is_current_employee,omitempty"`
	SessionId         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Upvotes           int32                   `protobuf:"varint,6,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	CreatedAt         *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompanyComment) Reset() {
	*x = CompanyComment{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyComment) ProtoMessage() {}

func (x *CompanyComment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyComment.ProtoReflect.Descriptor instead.
func (*CompanyComment) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *CompanyComment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompanyComment) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *CompanyComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CompanyComment) GetIsCurrentEmployee() bool {
	if x != nil {
		return x.IsCurrentEmployee
	}
	return false
}

func (x *CompanyComment) GetSessionId() *wrapperspb.StringValue {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CompanyComment) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *CompanyComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CommentRequest represents a comment submission
type CommentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CompanyId         int32                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Content           string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsCurrentEmployee bool                   `protobuf:"varint,3,opt,name=is_current_employee,json=isCurrentEmployee,proto3" json:"is_current_employee,omitempty"`
	SessionId         string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *CommentRequest) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *CommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentRequest) GetIsCurrentEmployee() bool {
	if x != nil {
		return x.IsCurrentEmployee
	}
	return false
}

func (x *CommentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// CommentList is a list of comments
type CommentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CompanyComment      `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentList) Reset() {
	*x = CommentList{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentList) ProtoMessage() {}

func (x *CommentList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentList.ProtoReflect.Descriptor instead.
func (*CommentList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *CommentList) GetComments() []*CompanyComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// LeaderboardRequest represents a leaderboard query
type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *LeaderboardRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LeaderboardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LeaderboardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// LeaderboardResponse represents the leaderboard data
type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderboardResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *LeaderboardResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *LeaderboardResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LeaderboardResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// StatsResponse represents overall platform stats
type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalCompanies int32                  `protobuf:"varint,1,opt,name=total_companies,json=totalCompanies,proto3" json:"total_companies,omitempty"`
	TotalVotes     int32                  `protobuf:"varint,2,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	TotalRatings   int32                  `protobuf:"varint,3,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`
	TotalComments  int32                  `protobuf:"varint,4,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	Categories     []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *StatsResponse) GetTotalCompanies() int32 {
	if x != nil {
		return x.TotalCompanies
	}
	return 0
}

func (x *StatsResponse) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *StatsResponse) GetTotalRatings() int32 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

func (x *StatsResponse) GetTotalComments() int32 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *StatsResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

// CategoryCount represents a category with its count
type CategoryCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCount) Reset() {
	*x = CategoryCount{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCount) ProtoMessage() {}

func (x *CategoryCount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCount.ProtoReflect.Descriptor instead.
func (*CategoryCount) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *CategoryCount) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// CategoryCountList is a list of category counts
type CategoryCountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryCount       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCountList) Reset() {
	*x = CategoryCountList{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCountList) ProtoMessage() {}

func (x *CategoryCountList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCountList.ProtoReflect.Descriptor instead.
func (*CategoryCountList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *CategoryCountList) GetCategories() []*CategoryCount {
	if x != nil {
		return x.Categories
	}
	return nil
}

// HealthResponse represents health check response
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetCompaniesRequest represents a request to get companies
type GetCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompaniesRequest) Reset() {
	*x = GetCompaniesRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompaniesRequest) ProtoMessage() {}

func (x *GetCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GetCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *GetCompaniesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetCompaniesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// GetCompanyRequest represents a request to get a single company
type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *GetCompanyRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// GetMatchupRequest represents a request to get a matchup
type GetMatchupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchupRequest) Reset() {
	*x = GetMatchupRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchupRequest) ProtoMessage() {}

func (x *GetMatchupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchupRequest.ProtoReflect.Descriptor instead.
func (*GetMatchupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *GetMatchupRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// UpvoteCommentRequest represents a request to upvote a comment
type UpvoteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int32                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpvoteCommentRequest) Reset() {
	*x = UpvoteCommentRequest{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpvoteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpvoteCommentRequest) ProtoMessage() {}

func (x *UpvoteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpvoteCommentRequest.ProtoReflect.Descriptor instead.
func (*UpvoteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *UpvoteCommentRequest) GetCommentId() int32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

// Empty message for requests/responses with no body
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9f\x06\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x127\n" +
	"\blogo_url\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\alogoUrl\x12>\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x126\n" +
	"\awebsite\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\awebsite\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12>\n" +
	"\ffounded_year\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueR\vfoundedYear\x12=\n" +
	"\vhq_location\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"hqLocation\x12C\n" +
	"\x0eemployee_range\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\remployeeRange\x12A\n" +
	"\rfunding_stage\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\ffundingStage\x12\x1d\n" +
	"\n" +
	"elo_rating\x18\r \x01(\x05R\teloRating\x12\x1f\n" +
	"\vtotal_votes\x18\x0e \x01(\x05R\n" +
	"totalVotes\x12\x12\n" +
	"\x04wins\x18\x0f \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x10 \x01(\x05R\x06losses\x12\x12\n" +
	"\x04rank\x18\x11 \x01(\x05R\x04rank\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\vCompanyList\x12*\n" +
	"\tcompanies\x18\x01 \x03(\v2\f.api.CompanyR\tcompanies\"\xc6\x01\n" +
	"\x04Vote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x05R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x03 \x01(\x05R\aloserId\x12;\n" +
	"\n" +
	"session_id\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\tsessionId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"d\n" +
	"\vVoteRequest\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\x05R\bwinnerId\x12\x19\n" +
	"\bloser_id\x18\x02 \x01(\x05R\aloserId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xa6\x01\n" +
	"\fVoteResponse\x12$\n" +
	"\x06winner\x18\x01 \x01(\v2\f.api.CompanyR\x06winner\x12\"\n" +
	"\x05loser\x18\x02 \x01(\v2\f.api.CompanyR\x05loser\x12&\n" +
	"\x0fwinner_elo_diff\x18\x03 \x01(\x05R\rwinnerEloDiff\x12$\n" +
	"\x0eloser_elo_diff\x18\x04 \x01(\x05R\floserEloDiff\"a\n" +
	"\vMatchupPair\x12(\n" +
	"\bcompany1\x18\x01 \x01(\v2\f.api.CompanyR\bcompany1\x12(\n" +
	"\bcompany2\x18\x02 \x01(\v2\f.api.CompanyR\bcompany2\"\xea\x01\n" +
	"\rCompanyRating\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x05R\tcompanyId\x12\x1c\n" +
	"\tcriterion\x18\x03 \x01(\tR\tcriterion\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12;\n" +
	"\n" +
	"session_id\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tsessionId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x81\x01\n" +
	"\rRatingRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x05R\tcompanyId\x12\x1c\n" +
	"\tcriterion\x18\x02 \x01(\tR\tcriterion\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"z\n" +
	"\x10AggregatedRating\x12\x1c\n" +
	"\tcriterion\x18\x01 \x01(\tR\tcriterion\x12#\n" +
	"\raverage_score\x18\x02 \x01(\x01R\faverageScore\x12#\n" +
	"\rtotal_ratings\x18\x03 \x01(\x05R\ftotalRatings\"G\n" +
	"\x14AggregatedRatingList\x12/\n" +
	"\aratings\x18\x01 \x03(\v2\x15.api.AggregatedRatingR\aratings\"\x9b\x02\n" +
	"\x0eCompanyComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x05R\tcompanyId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12.\n" +
	"\x13is_current_employee\x18\x04 \x01(\bR\x11isCurrentEmployee\x12;\n" +
	"\n" +
	"session_id\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tsessionId\x12\x18\n" +
	"\aupvotes\x18\x06 \x01(\x05R\aupvotes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x98\x01\n" +
	"\x0eCommentRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x05R\tcompanyId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12.\n" +
	"\x13is_current_employee\x18\x03 \x01(\bR\x11isCurrentEmployee\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\">\n" +
	"\vCommentList\x12/\n" +
	"\bcomments\x18\x01 \x03(\v2\x13.api.CompanyCommentR\bcomments\"a\n" +
	"\x12LeaderboardRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x93\x01\n" +
	"\x13LeaderboardResponse\x12*\n" +
	"\tcompanies\x18\x01 \x03(\v2\f.api.CompanyR\tcompanies\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc5\x01\n" +
	"\rStatsResponse\x12'\n" +
	"\x0ftotal_companies\x18\x01 \x01(\x05R\x0etotalCompanies\x12\x1f\n" +
	"\vtotal_votes\x18\x02 \x01(\x05R\n" +
	"totalVotes\x12#\n" +
	"\rtotal_ratings\x18\x03 \x01(\x05R\ftotalRatings\x12%\n" +
	"\x0etotal_comments\x18\x04 \x01(\x05R\rtotalComments\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\"A\n" +
	"\rCategoryCount\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"G\n" +
	"\x11CategoryCountList\x122\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x12.api.CategoryCountR\n" +
	"categories\"D\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"I\n" +
	"\x13GetCompaniesRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\"'\n" +
	"\x11GetCompanyRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"/\n" +
	"\x11GetMatchupRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"5\n" +
	"\x14UpvoteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x05R\tcommentId\"\a\n" +
	"\x05EmptyB+Z)github.com/cloutdotgg/backend/internal/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_goTypes = []any{
	(*Company)(nil),                // 0: api.Company
	(*CompanyList)(nil),            // 1: api.CompanyList
	(*Vote)(nil),                   // 2: api.Vote
	(*VoteRequest)(nil),            // 3: api.VoteRequest
	(*VoteResponse)(nil),           // 4: api.VoteResponse
	(*MatchupPair)(nil),            // 5: api.MatchupPair
	(*CompanyRating)(nil),          // 6: api.CompanyRating
	(*RatingRequest)(nil),          // 7: api.RatingRequest
	(*AggregatedRating)(nil),       // 8: api.AggregatedRating
	(*AggregatedRatingList)(nil),   // 9: api.AggregatedRatingList
	(*CompanyComment)(nil),         // 10: api.CompanyComment
	(*CommentRequest)(nil),         // 11: api.CommentRequest
	(*CommentList)(nil),            // 12: api.CommentList
	(*LeaderboardRequest)(nil),     // 13: api.LeaderboardRequest
	(*LeaderboardResponse)(nil),    // 14: api.LeaderboardResponse
	(*StatsResponse)(nil),          // 15: api.StatsResponse
	(*CategoryCount)(nil),          // 16: api.CategoryCount
	(*CategoryCountList)(nil),      // 17: api.CategoryCountList
	(*HealthResponse)(nil),         // 18: api.HealthResponse
	(*ErrorResponse)(nil),          // 19: api.ErrorResponse
	(*GetCompaniesRequest)(nil),    // 20: api.GetCompaniesRequest
	(*GetCompanyRequest)(nil),      // 21: api.GetCompanyRequest
	(*GetMatchupRequest)(nil),      // 22: api.GetMatchupRequest
	(*UpvoteCommentRequest)(nil),   // 23: api.UpvoteCommentRequest
	(*Empty)(nil),                  // 24: api.Empty
	(*wrapperspb.StringValue)(nil), // 25: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 26: google.protobuf.Int32Value
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	25, // 0: api.Company.logo_url:type_name -> google.protobuf.StringValue
	25, // 1: api.Company.description:type_name -> google.protobuf.StringValue
	25, // 2: api.Company.website:type_name -> google.protobuf.StringValue
	26, // 3: api.Company.founded_year:type_name -> google.protobuf.Int32Value
	25, // 4: api.Company.hq_location:type_name -> google.protobuf.StringValue
	25, // 5: api.Company.employee_range:type_name -> google.protobuf.StringValue
	25, // 6: api.Company.funding_stage:type_name -> google.protobuf.StringValue
	27, // 7: api.Company.created_at:type_name -> google.protobuf.Timestamp
	27, // 8: api.Company.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: api.CompanyList.companies:type_name -> api.Company
	25, // 10: api.Vote.session_id:type_name -> google.protobuf.StringValue
	27, // 11: api.Vote.created_at:type_name -> google.protobuf.Timestamp
	0,  // 12: api.VoteResponse.winner:type_name -> api.Company
	0,  // 13: api.VoteResponse.loser:type_name -> api.Company
	0,  // 14: api.MatchupPair.company1:type_name -> api.Company
	0,  // 15: api.MatchupPair.company2:type_name -> api.Company
	25, // 16: api.CompanyRating.session_id:type_name -> google.protobuf.StringValue
	27, // 17: api.CompanyRating.created_at:type_name -> google.protobuf.Timestamp
	8,  // 18: api.AggregatedRatingList.ratings:type_name -> api.AggregatedRating
	25, // 19: api.CompanyComment.session_id:type_name -> google.protobuf.StringValue
	27, // 20: api.CompanyComment.created_at:type_name -> google.protobuf.Timestamp
	10, // 21: api.CommentList.comments:type_name -> api.CompanyComment
	0,  // 22: api.LeaderboardResponse.companies:type_name -> api.Company
	16, // 23: api.CategoryCountList.categories:type_name -> api.CategoryCount
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
